language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
env: TMPDIR=/tmp
install:
 - phpenv rehash
services:
  - memcached
addons:
  mariadb: '10.3'
before_script:
  - phpenv config-rm xdebug.ini || return 0
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  
  - mysql -e 'create database zftest;'

  - phpenv config-add tests/php7_config.ini;

  - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php
  - php -i
script:
 - cd tests/
 - php runalltests.php
